[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SARVI"
version = "0.1.0"
description = "Extractor de diagnósticos y códigos CIE10 desde informes médicos"
readme = "README.md"
requires-python = ">=3.12,<3.13"
authors = [
    { name = "Julen Rodríguez Meneses", email = "jrodriguezme@unav.es" }
]

dependencies = [
    "pydantic>=2.0",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
]

# Tras `pip install -e .` se puede hacer:
#   SARVI --tarea docx_tp_jsons --modo sync
#   SARVI --tarea jsons_to_xlsx --modo async
[project.scripts]
mi-pipeline = "SARVI.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
