import os
import torch
import string
import contextlib
import numpy as np
import pandas as pd

from text_to_num import text2num
from stop_words import get_stop_words

from ....models.schemas import (
    Any
)
from .ner_utils import (
    parse_label_piece, candidate_identity
)

###
stopwords_es = list(set(get_stop_words('spanish')+list(string.ascii_lowercase)+["ñ","ç","ch"]))

@contextlib.contextmanager
def suppress_stderr():
    """
    Suppress stderr.

    Parameters
    ----------

    Returns
    -------
        `Any`
            - Derived value produced by the operation.
    """
    old_stderr = os.dup(2)
    devnull = os.open(os.devnull, os.O_WRONLY)
    try:
        os.dup2(devnull, 2)
        yield
    finally:
        os.dup2(old_stderr, 2)
        os.close(old_stderr)
        os.close(devnull)
###

def is_number(token: str):
    """
    Checks whether a token represents a number, whether in numeric format or written in English or Spanish.

    Parameters
    ----------
        `token`: str
            - The token to be evaluated as a possible number

    Returns
    -------
        ``: bool
            - `True` if the token can be interpreted as a number. Otherwise, returns `False`
    """
    token = str(token).strip("▁").strip()
    if not token:
        return False
    try:
        float(token.replace(",", "."))
        return True
    except Exception:
        pass

    lowered = token.lower().replace("-", " ").strip()
    if not lowered:
        return False

    for lang in ("en", "es"):
        try:
            with suppress_stderr():
                text2num(lowered, lang)
            return True
        except Exception:
            pass

    return False

def merge_sentencepiece_words(tokens: list):
    """
    Reconstructs complete words from tokens generated by a SentencePiece-type tokenizer

    Parameters
    ----------
        `tokens`: list
            - List of tokens. Tokens that begin with ` ` are interpreted as the start of a new word

    Returns
    -------
        `words`: list
            - List of words reconstructed from the original tokens
    """
    words = []
    current = []

    for tok in tokens:
        if tok.startswith("▁"):
            if current:
                words.append("".join(current))
            current = [tok[1:]]  # remove ▁
        else:
            if current:
                current.append(tok)
            else:
                current = [tok]

    if current:
        words.append("".join(current))

    return words

def is_punct(word: str):
    """
    Processes if word is formed only by punctuations

    Parameters
    ----------
        `word`: str
            - Word or token to evaluate

    Returns
    -------
        ``: bool
            - `True` if all characters in `word` are punctuation marks and the string is not empty. Otherwise, returns `False`
    """
    return all(ch in string.punctuation for ch in word) and len(word) > 0

def is_stopword_punct_or_number(word: str, stopwords_es: list):
    """
    Checks whether a word is a stopword, a punctuation mark, or a number.

    Parameters
    ----------
        `word`: str
            - The word to be evaluated

        `stopwords_es`: list
            - List of Spanish stopwords used as filtering criteria

    Returns
    -------
        ``: bool
            - `True` if the word is a stopword, punctuation mark, or number. Otherwise, returns `False`
    """
    word = word.strip().lower()
    return (word in stopwords_es or is_number(word) or is_punct(word))


def has_bad_surrounding(decoder:list, stopwords_es: list, limit_stopwords_surround: int):
    """
    Checks whether the content tokens in a span are surrounded by too many stopwords, numbers, or punctuation marks.

    Parameters
    ----------
        `decoder`: list
            - List of decoded tokens that make up the span

        `stopwords_es`: list
            - List of Spanish stopwords used to detect uninformative words

        `limit_stopwords_surround`: int
            - Maximum number of context words checked around each content word

    Returns
    -------
        ``: bool
            - `True` if the span has context considered problematic. Returns `False` if it finds a content word with acceptable context
    """
    words = merge_sentencepiece_words(decoder)
    span = limit_stopwords_surround + 1

    for i, word in enumerate(words):
        if is_stopword_punct_or_number(word, stopwords_es):
            continue

        # check right
        if i - span >= 0:
            left_words = words[i - span:i]
            if all(is_stopword_punct_or_number(w, stopwords_es) for w in left_words):
                return False

        # check left
        if i + span < len(words):
            right_words = words[i + 1:i + 1 + span]
            if all(is_stopword_punct_or_number(w, stopwords_es) for w in right_words):
                return False

    return True

def get_edge_words(decoder: list):
    """
    Retrieves the first and last words of a span after reconstructing the complete words from SentencePiece-type tokens.

    Parameters
    ----------
        `decoder`: list
            - List of decoded tokens that make up the span

    Returns
    -------
        ``: tuple
            - Tuple containing the first and last words in lowercase. If there are no words, returns **(“”, “”)**
    """
    words = merge_sentencepiece_words(decoder)

    if not words:
        return "", ""

    return words[0].lower(), words[-1].lower()

def safe_tensor_item(value: Any):
    """
    Processes safe tensor item for use by the pipeline.

    Parameters
    ----------
        `value`: Any
            - Value to validate or normalize.

    Returns
    -------
        `Any`
            - Derived value produced by the operation.
    """
    if torch.is_tensor(value):
        if value.numel() == 1:
            return value.item()
        return value.detach().cpu().tolist()

    if isinstance(value, np.generic):
        return value.item()

    return value

def label_value_to_str(value: Any, id2label: dict) -> str:
    """
    Processes label value to str for use by the pipeline.

    Parameters
    ----------
        `value`: Any
            - Value to validate or normalize.
        `id2label`: dict
            - Mapping from numeric identifiers to labels.

    Returns
    -------
        `str`
            - Derived value produced by the operation.
    """
    value = safe_tensor_item(value)

    if value is None:
        return "O"

    if isinstance(value, (int, np.integer)):
        if int(value) == -100:
            return "O"
        return str(id2label.get(int(value), "O"))

    value = str(value)
    if value == "-100":
        return "O"

    return value

def labels_for_window(data: dict, window_idx: int, id2label: dict) -> list[str] | None:
    """
    Gets the labels associated with one NER window.

    Parameters
    ----------
        `data`: dict
            - Input dataframe containing the records to process.
        `window_idx`: int
            - Index of the NER window.
        `id2label`: dict
            - Mapping from numeric identifiers to labels.

    Returns
    -------
        `list[str] | None`
            - List of parsed, filtered, or generated values.
    """
    labels = data.get("window_labels")

    if labels is None:
        return None

    try:
        if torch.is_tensor(labels):
            return [label_value_to_str(value, id2label) for value in labels[window_idx]]

        return [label_value_to_str(value, id2label) for value in labels[window_idx]]
    except Exception:
        return None

def label_piece_identity(piece: str, pos: int) -> dict | None:
    """
    Processes label piece identity for use by the pipeline.

    Parameters
    ----------
        `piece`: str
            - Argument controlling piece.
        `pos`: int
            - Argument controlling pos.

    Returns
    -------
        `dict | None`
            - Mapping containing the processed values.
    """
    parsed = parse_label_piece(piece, pos)

    if parsed is None:
        return None

    identity = candidate_identity(parsed)
    if identity is None:
        return None

    return {
        "identity": str(identity),
        "entity": parsed["entity"],
        "pos": int(pos),
        "raw": piece,
    }

def token_label_candidates(raw_label: str) -> list[dict]:
    """
    Expands a raw token label into possible candidate interpretations.

    Parameters
    ----------
        `raw_label`: str
            - Entity or relation labels used by the model.

    Returns
    -------
        `list[dict]`
            - List of parsed, filtered, or generated values.
    """
    if raw_label is None:
        return []

    candidates = []

    for pos, piece in enumerate(str(raw_label).split(";")):
        candidate = label_piece_identity(piece, pos)
        if candidate is not None:
            candidates.append(candidate)

    return candidates

def join_sentencepiece_tokens(tokens: list[str]) -> str:
    """
    Processes join sentencepiece tokens for use by the pipeline.

    Parameters
    ----------
        `tokens`: list[str]
            - Token data used for encoding or alignment.

    Returns
    -------
        `str`
            - Derived value produced by the operation.
    """
    return "".join((" " + token[1:]) if token.startswith("▁") else token for token in tokens).strip()

def lexicon_lemmas(lexicon: pd.DataFrame | None) -> set[str]:
    """
    Processes lexicon lemmas for use by the pipeline.

    Parameters
    ----------
        `lexicon`: pd.DataFrame | None
            - Optional lexicon used to score candidate spans.

    Returns
    -------
        `set[str]`
            - Derived value produced by the operation.
    """
    if lexicon is None or "lemma" not in lexicon.columns:
        return set()

    return {str(value).strip().lower() for value in lexicon["lemma"].dropna() if str(value).strip()}

def valid_words_for_weight(text: str, label: str, lexicon_lemma_set: set[str]) -> set[str]:
    """
    Extracts lexicon words that can contribute to span weighting.

    Parameters
    ----------
        `text`: str
            - Text containing the entity or span.
        `label`: str
            - Entity or relation label.
        `lexicon_lemma_set`: set[str]
            - Set of normalized lexicon lemmas.

    Returns
    -------
        `set[str]`
            - Derived value produced by the operation.
    """
    words = {word.strip(string.punctuation).lower() for word in text.split()}
    words = {word for word in words if word}

    if label == "DISO" and lexicon_lemma_set:
        return words & lexicon_lemma_set

    return {
        word
        for word in words
        if word not in string.punctuation
        and word not in stopwords_es
        and not is_number(word)
    }

def to_list(value: Any) -> list:
    """
    Processes to list for use by the pipeline.

    Parameters
    ----------
        `value`: Any
            - Value to validate or normalize.

    Returns
    -------
        `list`
            - List of parsed, filtered, or generated values.
    """
    value = safe_tensor_item(value)

    if isinstance(value, list):
        return value

    if isinstance(value, tuple):
        return list(value)

    try:
        return list(value)
    except TypeError:
        return [value]
